set local_atual=:cidade 
set /a cidade_atual=1 
set /a pos_x=5 
set /a pos_y=1 
set /a visitou_cidade_1= 
set "nome_personagem=Tulio" 
set "classe_personagem=O Mago" 
set /a lvl_jogador=1 
set /a xp_atual=0 
set /a xp_proximo_lvl=50 
set /a hp_jogador=10 
set /a max_hp=10 
set /a forca_jogador=5 
set /a agil_jogador=15 
set /a def_jogador=15 
set /a mana_jogador=30 
set /a max_mana=30 
set /a armamento=0 
set /a escudo=0 
set /a armadura=0 
set "nome_arma= Graveto" 
set "roupa=" 
set /a pocao_hp=1 
set /a pocao_mana=1 
set /a refeicao=0 
set /a ouro=50 
set /a slot=6 
set /a qtd_itens=2 
set "atk_especial_1=Bola de Fogo" 
set "atk_especial_2=Raio Congelante" 
set "atk_especial_3=Tempestade de Raios" 
set "atk_padrao=Ataque com Cajado" 
set "s1=   /\      " 
set "s2= _/__\_┏┓  " 
set "s3= ( o.o)┃   " 
set "s4= /(__)/┃   " 
set "s5=  /  \ ┃   " 
set "sp1=    /\      " 
set "sp2=┏┓_/__\_  " 
set "sp3= ┃(o.o )   " 
set "sp4= ┃\(__)\   " 
set "sp5= ┃ /  \    " 
