set local_atual=:cidade 
set /a cidade_atual=1 
set /a pos_x=5 
set /a pos_y=1 
set /a visitou_cidade=
set "nome_personagem=Soso" 
set "classe_personagem=A Ocultista" 
set /a lvl_jogador=1 
set /a xp_atual=0 
set /a xp_proximo_lvl=50 
set /a hp_jogador=12 
set /a max_hp=12 
set /a forca_jogador=10 
set /a agil_jogador=28 
set /a def_jogador=15 
set /a mana_jogador=10 
set /a max_mana=10 
set /a armamento=0 
set /a escudo=0 
set /a armadura=0 
set "nome_arma= Graveto" 
set "roupa=" 
set /a pocao_hp=1 
set /a pocao_mana=1 
set /a refeicao=0 
set /a ouro=30 
set /a slot=16 
set /a qtd_itens=2 
set "atk_especial_1=Golpe Soturno" 
set "atk_especial_2=Flecha Sombria" 
set "atk_especial_3=Invocação de Sombra" 
set "atk_padrao=Ataque com Adaga" 
set "s1=      .     " 
set "s2=     /_\   " 
set "s3=    (¬_¬)    " 
set "s4= ━┫╸━}_{━╺┣━" 
set "s5=    _/ \_    " 
set "sp1=" 
set "sp2=" 
set "sp3=" 
set "sp4=" 
set "sp5=" 
set "spr1=      .     " 
set "spr2=     /_\   " 
set "spr3=    (¬_¬)    " 
set "spr4= ━┫╸━}_{━╺┣━" 
set "spr5=    _/ \_    " 
